<!DOCTYPE html>
<html lang="ru">
<? require_once 'root-head.phtml' ?>
<body>
<div class="container">
    <div class="row">
        <div class="twelve columns" id="main-content">
            <h1>
                <?= $this->getTitle() ?>
            </h1>

            <div class="row">
                <?php
                $admin_auth_status = '';
                if ($this->data['admin-auth-result']['status'] == $this::ADMIN_AUTH_WRONG) {
                    $admin_auth_status = 'alert-error';
                } elseif (in_array($this->data['admin-auth-result']['status'], array($this::ADMIN_AUTH_EMPTY, $this::ADMIN_AUTH_ALREADY, $this::ADMIN_AUTH_LOGOUT))) {
                    $admin_auth_status = 'alert-info';
                } elseif ($this->data['admin-auth-result']['status'] == $this::ADMIN_AUTH_SUCCESS) {
                    $admin_auth_status = 'alert-success';
                } else {
                    $admin_auth_status = '';
                }
                ?>
                <div class="<?= $admin_auth_status ?>">
                    <p><?= $this->data['admin-auth-result']['message'] ?></p>
                </div>
                <? if ($this->data['admin-auth-result']['showAuthForm']): ?>
                    <div>
                        <form method="post" action="/admin/">
                            <label for="login">Логин</label>
                            <input type="text" name="login" id="login" value="admin"/>
                            <label for="password">Пароль</label>
                            <input type="password" name="password" id="password" value="pass" />
                            <br>
                            <button class="button button-primary">Войти</button>
                            <a href="/main/" target="_self" class="button">Вернуться на сайт</a>
                        </form>
                    </div>
                <? else: ?>
                    <div>
                        <p>
                            <a href="/main/" target="_self" class="button">Вернуться на сайт</a>
                            <a href="/admin/?logout=Y" target="_self" class="button">Выйти</a>
                        </p>
                    </div>
                <? endif ?>
            </div>
        </div>
    </div>
</div>
</body>
</html>