<!DOCTYPE html>
<html lang="ru">
<? require_once 'root-head.phtml' ?>
<body>
<div class="container">
    <div class="row">
        <div class="twelve columns" id="main-content">
            <h1>
                <?= $this->getTitle() ?>
            </h1>

            <div class="row">
                <?php
                $admin_auth_status = '';
                if ($this->data['admin-auth-result']['status'] == $this::ADMIN_AUTH_WRONG) {
                    $admin_auth_status = 'alert-error';
                } elseif ($this->data['admin-auth-result']['status'] == $this::ADMIN_AUTH_EMPTY) {
                    $admin_auth_status = 'alert-info';
                } elseif ($this->data['admin-auth-result']['status'] == $this::ADMIN_AUTH_SUCCESS) {
                    $admin_auth_status = 'alert-success';
                } else {
                    $admin_auth_status = '';
                }
                ?>
                <div class="<?= $admin_auth_status ?>">
                    <p><?= $this->data['admin-auth-result']['message'] ?></p>
                </div>
                <? if (!$this->data['admin-auth-result']['status']): ?>
                    <div>
                        <form method="post">
                            <label for="login">Логин</label>
                            <input type="text" name="login" id="login" value="<?= $this->data['login'] ?>"/>
                            <label for="password">Пароль</label>
                            <input type="password" name="password" id="password"
                                   value="<?= $this->data['password'] ?>"/>
                            <br>
                            <button class="button button-primary">Войти</button>
                        </form>
                    </div>
                <? else: ?>
                    <div>
                        <p>
                            Уже авторизован!!!
                        </p>
                    </div>
                <? endif ?>
            </div>
        </div>
    </div>
</div>
</body>
</html>