<!DOCTYPE html>
<html lang="ru">
<? require_once 'root-head.phtml' ?>
<body>
<? require_once 'root-header.phtml' ?>
<div class="container">
    <div class="row">
        <div class="three columns" id="sidebar-left">
            <? require 'newest-news.phtml' ?>
        </div>
        <div class="nine columns" id="main-content">
            <div class="row">
                <h3><?= $this->getTitle() ?></h3>

                <p>
                    Наша компания существует на Российском рынке
                </p>
            </div>
            <div class="row">
                <h4>Наша продукция</h4>

                <div class="row">
                    <? foreach ($this->data['products'] as $item): ?>
                        <div class="three columns product-list-item">
                            <a href="/product/<?= $item['category'] ?>/">
                                <img class="u-max-full-width" src="<?= $item['image'] ?>">
                                <span><?= $item['title'] ?></span>
                            </a>
                        </div>
                    <? endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <? require_once 'root-footer.phtml' ?>
</div>
</body>
</html>