<!DOCTYPE html>
<html lang="ru">
<? require_once 'root-head.phtml' ?>
<body>

<header>
    <div class="container">
        <div class="row">
            <div class="four columns">
                <h5><a href='/main/'><?= Settings::title ?></a></h5>
            </div>
            <div class="eight columns">
                <? require 'root-menu.phtml' ?>
            </div>
        </div>
        <div class="row">
            <div class="twelve columns" id="header-banner">
                <img src="http://placehold.it/875x140">
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="three columns" id="sidebar-left">
            <? require 'newest-news.phtml' ?>

        </div>
        <div class="nine columns" id="main-content">
            <h4><?= $this->page->getTitle() ?></h4>

            <p>
                Наша компания существует на Российском рынке
            </p>
        </div>
    </div>

</body>
</html>