<div class="news-block">
    <h3><a href="/news/">Новости компании</a></h3>
    <? foreach ($this->data['last-news'] as $article): ?>
        <div class="news-block-list">
            <dl class="news-block-list-item">
                <dt><?= date("d.m.Y", strtotime($article['created'])) ?></dt>
                <dd><a href="/news/<?= $article['id'] ?>/"><?= $article['title'] ?></a></dd>
            </dl>
        </div>
    <? endforeach ?>
</div>