<div class="news-block">
    <h3>Новости компании</h3>

    <div class="news-block-list">
        <dl class="news-block-list-item">
            <dt>10.07.2015</dt>
            <dd><a href="/news/2/">На Иннопроме роботы трудятся в полную силу</a></dd>
        </dl>
        <dl class="news-block-list-item">
            <dt>10.06.2015</dt>
            <dd><a href="/news/1/">Появление веб-сайта компании</a></dd>
        </dl>
    </div>
</div>