<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title><?= $this->page->getPageTitle() ?></title>
    <meta name="description" content="<#?= $page->meta->getDescription() ?>">
    <meta name="author" content="<#?= $page->meta->getAuthor() ?>">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS -->
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/normalize.css">
    <link rel="stylesheet" href="../static/css/skeleton.css">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="../static/images/favicon.ico">
</head>