<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title><?= $this->getPageTitle() ?></title>
    <meta name="description" content="<?= Settings::description ?>">
    <meta name="author" content="<?= Settings::author ?>">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS -->
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/skeleton.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.ico">
</head>