<header>
    <div class="container">
        <div class="row">
            <div class="four columns">
                <h5><a href='/main/'><?= Settings::title ?></a></h5>
            </div>
            <div class="eight columns">
                <? require 'root-menu.phtml' ?>
            </div>
        </div>
        <!--
        <div class="row">
            <div class="twelve columns" id="header-banner">
                <img class="u-full-width" src="http://placehold.it/875x140">
            </div>
        </div>
        -->
    </div>
</header>